# Generated by Django 4.2.21 on 2025-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_desc', models.TextField(max_length=255)),
                ('sub_desc', models.TextField(max_length=255)),
            ],
        ),
    ]
