# Generated by Django 5.2.1 on 2025-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdetail',
            name='image_url',
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
