# Generated by Django 4.2.21 on 2025-06-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_herocontent'),
        ('citizen', '0002_remove_complaintdetail_image_url_and_more'),
    ]

    operations = [
    ]
