# Generated by Django 5.2.1 on 2025-06-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_herocontent'),
        ('citizen', '0002_remove_complaintdetail_image_url_and_more'),
    ]

    operations = [
    ]
