# Generated by Django 4.2.21 on 2025-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_merge_20250606_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdetail',
            name='location',
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='address',
            field=models.CharField(default='Tamil Nadu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='district',
            field=models.CharField(default='chennai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='pincode',
            field=models.CharField(default=620001, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='state',
            field=models.CharField(default='default string', max_length=100),
            preserve_default=False,
        ),
    ]
