# Generated by Django 4.2.21 on 2025-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_merge_20250606_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField(max_length=255)),
                ('sub_title', models.TextField(max_length=255)),
            ],
        ),
    ]
