# Generated by Django 5.2.1 on 2025-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_merge_20250606_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetail',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
