# Generated by Django 4.2.21 on 2025-06-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Landing_media/'),
        ),
    ]
