# Generated by Django 4.2.21 on 2025-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_alter_testimonials_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, default='alert.png', null=True, upload_to=''),
        ),
    ]
