# Generated by Django 4.2.21 on 2025-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_alter_testimonials_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Landing_media/'),
        ),
    ]
