# Generated by Django 4.2.21 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0008_alter_testimonials_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.TextField(max_length=255)),
                ('faq_answer', models.TextField(max_length=255)),
            ],
        ),
    ]
