# Generated by Django 4.2.21 on 2025-06-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_remove_complaintdetail_location_and_more'),
        ('citizen', '0010_latest_news'),
    ]

    operations = [
    ]
