# Generated by Django 4.2.21 on 2025-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0011_merge_20250611_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaintdetail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
