# Generated by Django 4.2.21 on 2025-06-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_alter_complaintdetail_image_upload'),
        ('citizen', '0012_complaintdetail_latitude_complaintdetail_longitude'),
    ]

    operations = [
    ]
