# Generated by Django 5.2.1 on 2025-06-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0013_merge_20250612_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictLocation',
            fields=[
                ('distric_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StateLocation',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='complaintdetail',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.districtlocation'),
        ),
        migrations.AddField(
            model_name='districtlocation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.statelocation'),
        ),
        migrations.AlterField(
            model_name='complaintdetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.statelocation'),
        ),
    ]
